micronaut:
  application:
    name: demo
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
